/**
 * RP2350 Pure Data Firmware
 * 
 * Main firmware entry point for running Pure Data patches compiled with hvcc.
 */

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "pico/stdlib.h"
#include "pico/sync.h"
#include "pico/multicore.h"
#include "pico/audio.h"
#include "pico/audio_i2s.h"
#include "hardware/gpio.h"

// Firmware configuration
#include "config.h"
#include "multicore_audio.h"

// Include Heavy headers (generated by hvcc)
// Note: We always use "patch" as the Heavy project name for simplicity
// This means the generated header is always Heavy_patch.h
#include "Heavy_patch.h"
#include "HvHeavy.h"

// Patch API (single send hook owner; MIDI push helpers)
#include "patch_api.h"

// Optional WS2812 support
#ifdef ENABLE_WS2812
#include "dev/ws2812.h"
#endif

// Optional SSD1306 OLED (I2C) support
#ifdef ENABLE_OLED
#include "dev/oled.h"
#include "multicore_display.h"
#endif

// Optional USB MIDI support
#ifdef ENABLE_USB_MIDI
#include "tusb.h"
#include "usb/usb_cdc.h"
#include "usb/usb_midi.h"
#endif

// Audio configuration
#define SAMPLE_RATE 48000
#define AUDIO_BLOCK_SIZE 64  // Heavy default block size
#define AUDIO_BUFFER_SIZE (AUDIO_BLOCK_SIZE * 2)  // Stereo

// I2S pin configuration (config.h / config_local.h)
// DIN = PICO_AUDIO_I2S_DATA_PIN; clocks = PICO_AUDIO_I2S_CLOCK_PIN_BASE, base+1 (order by PICO_AUDIO_I2S_CLOCK_PINS_SWAPPED).

// Audio format
static const audio_format_t audio_format = {
    .sample_freq = SAMPLE_RATE,
    .format = AUDIO_BUFFER_FORMAT_PCM_S16,  // 16-bit signed PCM
    .channel_count = 2  // Stereo
};

// Audio buffer format (needed for buffer pool creation)
static audio_buffer_format_t audio_buffer_format = {
    .format = &audio_format,
    .sample_stride = 4  // 2 bytes per sample * 2 channels = 4 bytes per frame
};

// I2S configuration
static const audio_i2s_config_t i2s_config = {
    .data_pin = PICO_AUDIO_I2S_DATA_PIN,
    .clock_pin_base = PICO_AUDIO_I2S_CLOCK_PIN_BASE,
    .dma_channel = 0,  // Will be assigned automatically
    .pio_sm = 0  // PIO state machine 0
};

// Audio buffer pool for output
static audio_buffer_pool_t *audio_pool = NULL;

// Heavy context (will be initialized from generated code)
static HeavyContextInterface *heavy_context = NULL;


/**
 * Convert 16-bit integer samples to float (-1.0 to 1.0)
 */
static void int16_to_float(const int16_t *in, float *out, size_t count) {
    for (size_t i = 0; i < count; i++) {
        out[i] = (float)in[i] / 32768.0f;
    }
}

/**
 * Convert float samples (-1.0 to 1.0) to 16-bit integer
 */
static void float_to_int16(const float *in, int16_t *out, size_t count) {
    for (size_t i = 0; i < count; i++) {
        float sample = in[i];
        // Clamp to [-1.0, 1.0]
        if (sample > 1.0f) sample = 1.0f;
        if (sample < -1.0f) sample = -1.0f;
        out[i] = (int16_t)(sample * 32767.0f);
    }
}

/**
 * Audio core (core1) entry: drain ctrl queue, then produce one buffer via Heavy.
 * Invariant: no sleep, printf, I/O; only ctrl_queue drain, Heavy, buffer pool.
 */
static void audio_core_main(void) {
    static float audio_out_buffer[AUDIO_BUFFER_SIZE];
    while (true) {
        if (audio_pool == NULL || heavy_context == NULL) {
            continue;
        }
        multicore_drain_ctrl(heavy_context);
        audio_buffer_t *buffer = take_audio_buffer(audio_pool, true);
        if (buffer == NULL) {
            continue;
        }
        int16_t *samples = (int16_t *)buffer->buffer->bytes;
        size_t samples_per_channel = buffer->max_sample_count;
        size_t blocks_to_process = (samples_per_channel + AUDIO_BLOCK_SIZE - 1) / AUDIO_BLOCK_SIZE;
        for (size_t block = 0; block < blocks_to_process; block++) {
            size_t block_size = AUDIO_BLOCK_SIZE;
            if (block == blocks_to_process - 1) {
                block_size = samples_per_channel - (block * AUDIO_BLOCK_SIZE);
            }
            hv_processInlineInterleaved(heavy_context, NULL, audio_out_buffer, block_size);
#ifdef ENABLE_OLED
            // Publish a downsampled waveform for the OLED (core1 only; no I/O).
            multicore_display_capture_interleaved(audio_out_buffer, block_size);
#endif
            float_to_int16(audio_out_buffer,
                           samples + (block * AUDIO_BLOCK_SIZE * 2),
                           block_size * 2);
        }
        buffer->sample_count = samples_per_channel;
        give_audio_buffer(audio_pool, buffer);
    }
}

int main() {
#ifdef ENABLE_USB_MIDI
    // Custom TinyUSB initialization for CDC+MIDI
    tusb_init();
    
    // Service USB immediately after init for enumeration
    // Critical: USB must be serviced quickly for host to recognize device
    for (int i = 0; i < 100; i++) {
        tud_task();
        sleep_ms(1);
    }
    
    // Initialize USB CDC for printf
    usb_cdc_init();
    
    printf("\n=== RP2350 Pure Data Firmware ===\n");
    printf("USB MIDI Mode: CDC+MIDI composite device\n");
    printf("Initializing...\n");
#else
    // Standard stdio initialization (pico_stdio_usb)
    stdio_init_all();
    
    // Wait a bit for USB serial to be ready
    sleep_ms(100);
    
    printf("\n=== RP2350 Pure Data Firmware ===\n");
    printf("Standard Mode: CDC only (no MIDI)\n");
    printf("Initializing...\n");
#endif
    
    // Setup I2S audio output
    const audio_format_t *output_format = audio_i2s_setup(&audio_format, &i2s_config);
    if (output_format == NULL) {
        printf("ERROR: Failed to setup I2S audio\n");
        printf("Continuing without audio...\n");
        // Don't return -1, continue to main loop for debugging
    }
    // No special I2S GPIO configuration required for this use case.
    printf("I2S audio setup successful\n");
    printf("  Sample rate: %d Hz\n", output_format->sample_freq);
    printf("  Format: %d, Channels: %d\n", output_format->format, output_format->channel_count);
    
    // Create audio buffer pool for output (only if I2S setup succeeded)
    if (output_format != NULL) {
        audio_pool = audio_new_producer_pool(&audio_buffer_format, 3, AUDIO_BLOCK_SIZE);
        if (audio_pool == NULL) {
            printf("ERROR: Failed to create audio buffer pool\n");
        } else {
            // Connect audio producer to I2S output
            if (!audio_i2s_connect(audio_pool)) {
                printf("ERROR: Failed to connect audio to I2S\n");
            } else {
                // Enable I2S audio output
                audio_i2s_set_enabled(true);
                printf("Audio I2S connected and enabled\n");
            }
        }
    }

    multicore_audio_init();

    // Initialize Heavy context
    // Note: Function name is always hv_patch_new() since we use "patch" as project name
    heavy_context = hv_patch_new((double)SAMPLE_RATE);
    if (heavy_context == NULL) {
        printf("ERROR: Failed to create Heavy context\n");
        return -1;
    }
    printf("Heavy context created (sample rate: %d Hz)\n", SAMPLE_RATE);

    /* Single entry point for send hook: only patch_api_init() calls hv_setSendHook() */
    patch_api_init(heavy_context);

#ifdef ENABLE_USB_MIDI
    usb_midi_init();
#endif

#ifdef ENABLE_WS2812
    if (ws2812_init_with_hook(WS2812_PIN, WS2812_NUM_LEDS, heavy_context)) {
        printf("WS2812 initialized (pin: %d, LEDs: %d)\n", WS2812_PIN, WS2812_NUM_LEDS);
    } else {
        printf("WARNING: WS2812 initialization failed\n");
    }
#endif

#ifdef ENABLE_OLED
    if (oled_init()) {
        printf("OLED initialized (SSD1306 I2C, addr 0x%02X)\n", OLED_I2C_ADDR);
    } else {
        printf("WARNING: OLED initialization failed\n");
    }
#endif

    __sync_synchronize();
    multicore_launch_core1(audio_core_main);
    printf("Entering main loop (core0)...\n");

    while (true) {
#ifdef ENABLE_USB_MIDI
        tud_task();
        usb_midi_task();
#endif
        multicore_drain_led();
#ifdef ENABLE_OLED
        oled_task();
#endif
        sleep_us(100);
    }
    
    // Cleanup (unreachable in current implementation)
    if (heavy_context != NULL) {
        hv_patch_free(heavy_context);
    }
    
    return 0;
}
