/**
 * RP2350 Pure Data Firmware
 * 
 * Main firmware entry point for running Pure Data patches compiled with hvcc.
 */

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "pico/stdlib.h"
#include "pico/sync.h"
#include "pico/time.h"
#include "pico/multicore.h"
#include "pico/audio.h"
#include "pico/audio_i2s.h"
#include "hardware/gpio.h"

// Firmware configuration
#include "config.h"
#include "debug.h"
#include "multicore_audio.h"
#include "drv/i2c_bus.h"

// Include Heavy headers (generated by hvcc)
// Note: We always use "patch" as the Heavy project name for simplicity
// This means the generated header is always Heavy_patch.h
#include "Heavy_patch.h"
#include "HvHeavy.h"

// Patch API (single send hook owner; MIDI push helpers)
#include "patch_api.h"

// Optional WS2812 support
#ifdef ENABLE_WS2812
#include "dev/ws2812.h"
#endif

// Potentiometers (knob1..knob4) when POTS_BACKEND=ADC
#if (POTS_BACKEND == POTS_BACKEND_ADC)
#include "dev/adc_pots.h"
#endif

// Optional SSD1306 OLED (I2C) support
#ifdef ENABLE_OLED
#include "dev/oled.h"
#include "multicore_display.h"
#endif

// Optional MPR121 capacitive touch (I2C, touch1..touch12 @hv_param)
#ifdef ENABLE_MPR121
#include "dev/mpr121_touch.h"
#endif

// USB (TinyUSB device stack)
#include "tusb.h"
#include "usb/usb_cdc.h"

// Optional USB MIDI support
#ifdef ENABLE_USB_MIDI
#include "usb/usb_midi.h"
#endif

// Audio configuration
#define SAMPLE_RATE 48000
#define AUDIO_BLOCK_SIZE 64  // Heavy default block size
#define AUDIO_BUFFER_SIZE (AUDIO_BLOCK_SIZE * 2)  // Stereo
#define INT16_MAX_VALUE 32767.0f

// USB initialization
#define USB_INIT_ITERATIONS 100
#define USB_INIT_DELAY_MS 1

// Main loop
#define MAIN_LOOP_SLEEP_US 100

// I2S pin configuration (config.h / config_local.h)
// DIN = PICO_AUDIO_I2S_DATA_PIN; clocks = PICO_AUDIO_I2S_CLOCK_PIN_BASE, base+1 (order by PICO_AUDIO_I2S_CLOCK_PINS_SWAPPED).

// Audio format
static const audio_format_t audio_format = {
    .sample_freq = SAMPLE_RATE,
    .format = AUDIO_BUFFER_FORMAT_PCM_S16,  // 16-bit signed PCM
    .channel_count = 2  // Stereo
};

// Audio buffer format (needed for buffer pool creation)
static audio_buffer_format_t audio_buffer_format = {
    .format = &audio_format,
    .sample_stride = 4  // 2 bytes per sample * 2 channels = 4 bytes per frame
};

// I2S configuration
static const audio_i2s_config_t i2s_config = {
    .data_pin = PICO_AUDIO_I2S_DATA_PIN,
    .clock_pin_base = PICO_AUDIO_I2S_CLOCK_PIN_BASE,
    .dma_channel = 0,  // Will be assigned automatically
    .pio_sm = 0  // PIO state machine 0
};

// Audio buffer pool for output
static audio_buffer_pool_t *audio_pool = NULL;

// Heavy context (will be initialized from generated code)
static HeavyContextInterface *heavy_context = NULL;
static bool audio_ready;

#if (POTS_BACKEND == POTS_BACKEND_ADC)
static float pots_last_sent[POTS_MAX];
static uint32_t pots_last_poll_ms;
#endif


/**
 * Convert float samples (-1.0 to 1.0) to 16-bit integer
 */
static void float_to_int16(const float *in, int16_t *out, size_t count) {
    for (size_t i = 0; i < count; i++) {
        float sample = in[i];
        // Clamp to [-1.0, 1.0]
        if (sample > 1.0f) sample = 1.0f;
        if (sample < -1.0f) sample = -1.0f;
        out[i] = (int16_t)(sample * INT16_MAX_VALUE);
    }
}

/**
 * Audio core (core1) entry: drain ctrl queue, then produce one buffer via Heavy.
 * Invariant: no sleep, printf, I/O; only ctrl_queue drain, Heavy, buffer pool.
 */
static void audio_core_main(void) {
    static float audio_out_buffer[AUDIO_BUFFER_SIZE];
    while (true) {
        if (audio_pool == NULL || heavy_context == NULL) {
            continue;
        }
        multicore_drain_ctrl(heavy_context);
        audio_buffer_t *buffer = take_audio_buffer(audio_pool, true);
        if (buffer == NULL) {
            continue;
        }
        int16_t *samples = (int16_t *)buffer->buffer->bytes;
        size_t samples_per_channel = buffer->max_sample_count;
        size_t blocks_to_process = (samples_per_channel + AUDIO_BLOCK_SIZE - 1) / AUDIO_BLOCK_SIZE;
        for (size_t block = 0; block < blocks_to_process; block++) {
            size_t block_size = AUDIO_BLOCK_SIZE;
            if (block == blocks_to_process - 1) {
                block_size = samples_per_channel - (block * AUDIO_BLOCK_SIZE);
            }
            hv_processInlineInterleaved(heavy_context, NULL, audio_out_buffer, block_size);
#ifdef ENABLE_OLED
            // Publish a downsampled waveform for the OLED (core1 only; no I/O).
            multicore_display_capture_interleaved(audio_out_buffer, block_size);
#endif
            float_to_int16(audio_out_buffer,
                           samples + (block * AUDIO_BLOCK_SIZE * 2),
                           block_size * 2);
        }
        buffer->sample_count = samples_per_channel;
        give_audio_buffer(audio_pool, buffer);
    }
}

static void init_usb_subsystem(void) {
    // TinyUSB initialization (CDC always; MIDI optional)
    tusb_init();

    // Service USB immediately after init for enumeration
    // Critical: USB must be serviced quickly for host to recognize device
    for (int i = 0; i < USB_INIT_ITERATIONS; i++) {
        tud_task();
        sleep_ms(USB_INIT_DELAY_MS);
    }

    // Initialize USB CDC for printf
    usb_cdc_init();

    LOG_INFO("=== RP2350 Pure Data Firmware ===");
#ifdef ENABLE_USB_MIDI
    LOG_INFO("USB Mode: CDC+MIDI composite device");
#else
    LOG_INFO("USB Mode: CDC only (no MIDI)");
#endif
    LOG_INFO("Initializing...");
}

static void init_audio_subsystem(void) {
    // Setup I2S audio output
    const audio_format_t *output_format = audio_i2s_setup(&audio_format, &i2s_config);
    if (output_format == NULL) {
        LOG_ERROR("Failed to setup I2S audio");
        LOG_WARN("Continuing without audio...");
        // Don't return -1, continue to main loop for debugging
        return;
    }

    // No special I2S GPIO configuration required for this use case.
    LOG_INFO("I2S audio setup successful");
    LOG_INFO("  Sample rate: %d Hz", output_format->sample_freq);
    LOG_INFO("  Format: %d, Channels: %d", output_format->format, output_format->channel_count);

    // Create audio buffer pool for output (only if I2S setup succeeded)
    audio_pool = audio_new_producer_pool(&audio_buffer_format, 3, AUDIO_BLOCK_SIZE);
    if (audio_pool == NULL) {
        LOG_ERROR("Failed to create audio buffer pool");
        return;
    }

    // Connect audio producer to I2S output
    if (!audio_i2s_connect(audio_pool)) {
        LOG_ERROR("Failed to connect audio to I2S");
        return;
    }

    // Enable I2S audio output
    audio_i2s_set_enabled(true);
    audio_ready = true;
    LOG_INFO("Audio I2S connected and enabled");
}

static bool init_heavy_context(void) {
    // Initialize Heavy context
    // Note: Function name is always hv_patch_new() since we use "patch" as project name
    heavy_context = hv_patch_new((double)SAMPLE_RATE);
    if (heavy_context == NULL) {
        LOG_ERROR("Failed to create Heavy context");
        return false;
    }
    LOG_INFO("Heavy context created (sample rate: %d Hz)", SAMPLE_RATE);

    /* Single entry point for send hook: only patch_api_init() calls hv_setSendHook() */
    patch_api_init(heavy_context);
    return true;
}

static bool soft_reboot_patch_runtime(void) {
    // Keep USB alive; restart patch/audio runtime only.
    LOG_WARN("Soft reboot: restarting patch runtime");

    // Stop audio output to avoid underflows/glitches while core1 is down.
    if (audio_ready) {
        audio_i2s_set_enabled(false);
    }

    multicore_reset_core1();

    // Clear any queued events from the previous runtime.
    {
        hv_event_t ev;
        while (queue_try_remove(&ctrl_queue, &ev)) {
            (void)0;
        }
    }
    {
        led_cmd_t cmd;
        while (queue_try_remove(&led_queue, &cmd)) {
            (void)0;
        }
    }

    if (heavy_context != NULL) {
        hv_patch_free(heavy_context);
        heavy_context = NULL;
    }

    if (!init_heavy_context()) {
        LOG_ERROR("Soft reboot: hv_patch_new failed");
        return false;
    }

    __sync_synchronize();
    multicore_launch_core1(audio_core_main);

    if (audio_ready) {
        audio_i2s_set_enabled(true);
    }

    LOG_INFO("Soft reboot: done");
    return true;
}

static void init_peripherals(HeavyContextInterface *ctx) {
#ifdef ENABLE_USB_MIDI
    usb_midi_init();
#endif

#ifdef ENABLE_WS2812
    if (ws2812_init_with_hook(WS2812_PIN, WS2812_NUM_LEDS, ctx)) {
        LOG_INFO("WS2812 initialized (pin: %d, LEDs: %d)", WS2812_PIN, WS2812_NUM_LEDS);
    } else {
        LOG_WARN("WS2812 initialization failed");
    }
#endif

#ifdef ENABLE_OLED
    if (oled_init()) {
        LOG_INFO("OLED initialized (SSD1306 I2C, addr 0x%02X)", OLED_I2C_ADDR);
    } else {
        LOG_WARN("OLED initialization failed");
    }
#endif

#ifdef ENABLE_MPR121
    if (mpr121_touch_init()) {
        LOG_INFO("MPR121 touch initialized (IRQ GPIO%d, addr 0x%02X)", MPR121_IRQ_PIN, MPR121_I2C_ADDR);
    } else {
        LOG_WARN("MPR121 touch initialization failed");
    }
#endif

#if (POTS_BACKEND == POTS_BACKEND_ADC)
    if (POTS_COUNT > 0) {
        if (adc_pots_init()) {
            for (int i = 0; i < POTS_MAX && i < POTS_COUNT; i++) {
                pots_last_sent[i] = -1.f;
            }
            pots_last_poll_ms = 0;
            LOG_INFO("ADC pots initialized (knob1..knob%u, poll %d ms)", (unsigned)POTS_COUNT, POTS_POLL_MS);
        } else {
            LOG_WARN("ADC pots disabled (init failed).");
            LOG_INFO("  ADC channels: %u..%u",
                     (unsigned)POTS_ADC_FIRST_CHANNEL,
                     (unsigned)(POTS_ADC_FIRST_CHANNEL + POTS_COUNT - 1));
            LOG_INFO("  GPIO mapping depends on chip:");
            LOG_INFO("    RP2040/RP2350A: ch0-3 = GPIO26-29");
            LOG_INFO("    RP2350B: ch0-7 = GPIO40-47");
        }
    }
#endif
}

static void poll_adc_pots(void) {
#if (POTS_BACKEND == POTS_BACKEND_ADC)
    if (POTS_COUNT > 0) {
        uint32_t now = to_ms_since_boot(get_absolute_time());
        if (now - pots_last_poll_ms >= (uint32_t)POTS_POLL_MS) {
            pots_last_poll_ms = now;
            float v[POTS_MAX];
            adc_pots_read(v, (unsigned)POTS_COUNT);
            for (unsigned i = 0; i < (unsigned)POTS_COUNT && i < (unsigned)POTS_MAX; i++) {
                float diff = v[i] - pots_last_sent[i];
                if (pots_last_sent[i] < 0.f || (diff > POTS_EPS || -diff > POTS_EPS)) {
                    if (patch_api_push_knob((uint8_t)i, v[i]))
                        pots_last_sent[i] = v[i];
                    /* On ctrl_queue overflow (false): skip updating last_sent so the next poll may retry. */
                }
            }
        }
    }
#endif
}

int main() {
    init_usb_subsystem();
    init_audio_subsystem();
    multicore_audio_init();
    if (!init_heavy_context()) {
        return -1;
    }
    init_peripherals(heavy_context);

    __sync_synchronize();
    multicore_launch_core1(audio_core_main);
    LOG_INFO("Entering main loop (core0)...");

    while (true) {
        tud_task();
#ifdef ENABLE_USB_MIDI
        static bool last_midi_mounted;
        bool now_midi_mounted = usb_midi_mounted();
        if (now_midi_mounted != last_midi_mounted) {
            LOG_INFO("USB MIDI %s", now_midi_mounted ? "mounted" : "unmounted");
            last_midi_mounted = now_midi_mounted;
        }
#endif
        usb_cdc_task();
        if (usb_cdc_take_soft_reboot_request()) {
            (void)soft_reboot_patch_runtime();
        }
#ifdef ENABLE_USB_MIDI
        usb_midi_task();
#endif
        multicore_drain_led();
        i2c_bus_poll();
#ifdef ENABLE_MPR121
        mpr121_touch_task();
#endif
#ifdef ENABLE_OLED
        oled_task();
#endif
        poll_adc_pots();
        sleep_us(MAIN_LOOP_SLEEP_US);
    }

    // Cleanup (unreachable in current implementation)
    if (heavy_context != NULL) {
        hv_patch_free(heavy_context);
    }

    return 0;
}
